# Project C: Creating an Orbital Simulator/Integrator

In the "Differential_Equations_\*\*.ipynb" notebooks, we learned how to solve differential equations using the `scipy.integrate.solve_ivp` function. 

In the project you will create a module named `orbit_integrator` capable of simulating the orbits of stars and planets as they gravitationally interact with one another. 

Your module should be structured to contain the following 

```python
    orbit_integrator.py
        read_input
        ...
        integrate
        plot & animate
        run_project
```

## Project Specification 
The overall goal of the project is to 
 - read in the inital conditions: these will be the initial positions & velocities of the stars and planets, as well as their masses;
 - *integrate* the positions & velocities forward in time using `scipy.integrate.solve_ivp`
 - produce an animation (using the `animation` package) showing the evolution of the positions of the stars and planets

In detail, you should ...

In [55]:
X = np.array( [ [1,1], [0,3], [4,5], [1,0]])
X 

array([[1, 1],
       [0, 3],
       [4, 5],
       [1, 0]])

In [56]:
X.T

array([[1, 0, 4, 1],
       [1, 3, 5, 0]])

In [57]:
X @ X.T

array([[ 2,  3,  9,  1],
       [ 3,  9, 15,  0],
       [ 9, 15, 41,  4],
       [ 1,  0,  4,  1]])

In [58]:
diag = np.einsum('ii->i', X @ X.T)
diag 

array([ 2,  9, 41,  1])

In [59]:
diag = np.diag(X @ X.T)
diag

array([ 2,  9, 41,  1])

In [60]:
diag[:, None]

array([[ 2],
       [ 9],
       [41],
       [ 1]])

In [61]:
diag + diag[:, None]

array([[ 4, 11, 43,  3],
       [11, 18, 50, 10],
       [43, 50, 82, 42],
       [ 3, 10, 42,  2]])

In [69]:
m = X @ X.T
m

array([[ 2,  3,  9,  1],
       [ 3,  9, 15,  0],
       [ 9, 15, 41,  4],
       [ 1,  0,  4,  1]])

In [71]:
norms = np.diag(m)
norms

array([ 2,  9, 41,  1])

In [78]:
norms[:, None]

array([[ 2],
       [ 9],
       [41],
       [ 1]])

In [83]:
norms + norms[:, None] 

array([[ 4, 11, 43,  3],
       [11, 18, 50, 10],
       [43, 50, 82, 42],
       [ 3, 10, 42,  2]])

In [102]:
d2 = np.array( -2 * X @ X.T ).astype(float)
diag = -0.5 * np.einsum('ii->i', d2)
d2

array([[ -4.,  -6., -18.,  -2.],
       [ -6., -18., -30.,   0.],
       [-18., -30., -82.,  -8.],
       [ -2.,   0.,  -8.,  -2.]])

In [103]:
diag

array([ 2.,  9., 41.,  1.])

In [104]:
diag + diag[:, None]

array([[ 4., 11., 43.,  3.],
       [11., 18., 50., 10.],
       [43., 50., 82., 42.],
       [ 3., 10., 42.,  2.]])

In [105]:
d2 += np.array(diag + diag[:, None])
d2

array([[ 0.,  5., 25.,  1.],
       [ 5.,  0., 20., 10.],
       [25., 20.,  0., 34.],
       [ 1., 10., 34.,  0.]])